# Python

In [16]:
### Importando bibliotecas

import pandas as pd

In [17]:
### Lendo arquivo e renomeando colunas

filename = 'K3241.K03200Y9.D30311.ESTABELE.csv'
columns = ['CNPJ_BÁSICO',
           'CNPJ_ORDEM ',
           'CNPJ_DV',
           'IDENTIFICADOR_MATRIZ/FILIAL',
           'NOME_FANTASIA',
           'SITUAÇÃO_CADASTRAL',
           'DATA_SITUAÇÃO_CADASTRAL',
           'MOTIVO_SITUAÇÃO_CADASTRAL',
           'NOME_DA_CIDADE_NO_EXTERIOR',
           'PAIS',
           'DATA_DE_INÍCIO_ATIVIDADE ',
           'CNAE_FISCAL_PRINCIPAL',
           'CNAE_FISCAL_SECUNDÁRIA',
           'TIPO_DE_LOGRADOURO',
           'LOGRADOURO',
           'NÚMERO',
           'COMPLEMENTO',
           'BAIRRO',
           'CEP',
           'UF',
           'MUNICÍPIO',
           'DDD_1',
           'TELEFONE_1',
           'DDD_2',
           'TELEFONE_2',
           'DDD_DO_FAX',
           'FAX',
           'CORREIO_ELETRÔNICO',
           'SITUAÇÃO_ESPECIAL',
           'DATA_DA_SITUAÇÃO_ESPECIAL']
df = pd.read_csv(filename, sep=';', names = columns, encoding='latin-1')

C:\Users\levim\AppData\Local\Temp\ipykernel_5512\703044013.py:34: DtypeWarning: Columns (8,18,21,22,24,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(filename, sep=';', names = columns, encoding='latin-1')

In [18]:
### Vendo numero de linhas e colunas

df.shape

(4753435, 30)

In [19]:
### Criando colunas CNPJ COMPLETO e TELEFONE

df['CNPJ_COMPLETO'] = df['CNPJ_BÁSICO'].astype(str) + df['CNPJ_ORDEM '].astype(str) + df['CNPJ_DV'].astype(str)
df['TELEFONE'] = df['DDD_1'].astype(str) + "/" + df['TELEFONE_1'].astype(str)

In [20]:
### separado colunas

dfreg = df.sample(10)
dfreg['TELEFONE'] = dfreg['TELEFONE'].str.replace('.0', '')
dfreg.sample(10)

,CNPJ_BÁSICO,CNPJ_ORDEM,CNPJ_DV,IDENTIFICADOR_MATRIZ/FILIAL,NOME_FANTASIA,SITUAÇÃO_CADASTRAL,DATA_SITUAÇÃO_CADASTRAL,MOTIVO_SITUAÇÃO_CADASTRAL,NOME_DA_CIDADE_NO_EXTERIOR,PAIS,...,TELEFONE_1,DDD_2,TELEFONE_2,DDD_DO_FAX,FAX,CORREIO_ELETRÔNICO,SITUAÇÃO_ESPECIAL,DATA_DA_SITUAÇÃO_ESPECIAL,CNPJ_COMPLETO,TELEFONE
4187457,25320578,1,56,1,DISTRIBUIDORA DE BEBIDAS ARAUJO,8,20210617,1,NaN,NaN,...,44119688.0,11.0,24270992.0,11.0,24270992,CONCEITONIC@GMAIL.COM,NaN,NaN,25320578156,11/44119688
3475909,15534700,1,33,1,NaN,8,20180314,1,NaN,NaN,...,32441217.0,NaN,NaN,NaN,NaN,jairmbueno@yahoo.com.br,NaN,NaN,15534700133,35/32441217
234771,37253729,1,80,1,I R D GAS,4,20221202,63,NaN,NaN,...,34935448,NaN,NaN,NaN,NaN,DSILVA@BREVITY.COM.BR,NaN,NaN,37253729180,11/34935448
946414,48894826,1,78,1,NaN,2,20221214,0,NaN,NaN,...,47237824.0,NaN,NaN,NaN,NaN,IMPOSTOS@RIOVERDEBRASIL.COM,NaN,NaN,48894826178,15/47237824
3098445,13190217,1,53,1,NaN,2,20110113,0,NaN,NaN,...,32454095,17.0,96221936.0,17.0,32453442.0,LARISSAaNHOATO@HOTMAIL.COM,NaN,NaN,13190217153,17/32454095
1516750,1192680,1,55,1,NaN,8,20020313,1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1192680155,nan/nan
2922272,10782307,1,45,1,D REI MALHARIA,4,20210219,63,NaN,NaN,...,34461250.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10782307145,91/34461250
1591473,6355294,1,50,1,NaN,8,20150721,1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6355294150,nan/nan
4391716,25759075,1,81,1,NaN,8,20161231,1,NaN,NaN,...,0,NaN,NaN,28.0,35472297,sonia.cassandri@hotmail.com,NaN,NaN,25759075181,0/0
207819,41811867,1,4,1,NICOLAS PALACIOS,2,20210504,0,NaN,NaN,...,26050482.0,NaN,NaN,NaN,NaN,NICOLAS.PPAPA@GMAIL.COM,NaN,NaN,4181186714,11/26050482

In [21]:
### Criando pivot_table apenas com as colunas que serão utilizadas

registros = dfreg.pivot_table(
    index='CNPJ_COMPLETO',
    values=['NOME_FANTASIA', 'CEP', 'TELEFONE', 'CORREIO_ELETRÔNICO'],
    aggfunc='first'
)
registros.sample(10)

,CEP,CORREIO_ELETRÔNICO,NOME_FANTASIA,TELEFONE
CNPJ_COMPLETO,,,,
6355294150,96825750.0,None,None,nan/nan
10782307145,68660000.0,None,D REI MALHARIA,91/34461250
4181186714,2035020.0,NICOLAS.PPAPA@GMAIL.COM,NICOLAS PALACIOS,11/26050482
25320578156,12951280.0,CONCEITONIC@GMAIL.COM,DISTRIBUIDORA DE BEBIDAS ARAUJO,11/44119688
48894826178,18720000.0,IMPOSTOS@RIOVERDEBRASIL.COM,None,15/47237824
25759075181,29370000.0,sonia.cassandri@hotmail.com,None,0/0
1192680155,3975000.0,None,None,nan/nan
13190217153,15200000.0,LARISSAaNHOATO@HOTMAIL.COM,None,17/32454095
15534700133,37498000.0,jairmbueno@yahoo.com.br,None,35/32441217
37253729180,8223000.0,DSILVA@BREVITY.COM.BR,I R D GAS,11/34935448

In [22]:
### Salvando arquivo em csv com apenas 10 registros

registros.sample(10).to_csv('estabelecimentos10.csv')

In [23]:
### Transformando arquivo csv em json

df = pd.read_csv('estabelecimentos10.csv')
df = df.fillna('None')
estabelecimentos_data = df.to_dict(orient = "records")
estabelecimentos_data

[{'CNPJ_COMPLETO': 10782307145,
  'CEP': 68660000.0,
  'CORREIO_ELETRÔNICO': 'None',
  'NOME_FANTASIA': 'D REI MALHARIA',
  'TELEFONE': '91/34461250'},
 {'CNPJ_COMPLETO': 1192680155,
  'CEP': 3975000.0,
  'CORREIO_ELETRÔNICO': 'None',
  'NOME_FANTASIA': 'None',
  'TELEFONE': 'nan/nan'},
 {'CNPJ_COMPLETO': 48894826178,
  'CEP': 18720000.0,
  'CORREIO_ELETRÔNICO': 'IMPOSTOS@RIOVERDEBRASIL.COM',
  'NOME_FANTASIA': 'None',
  'TELEFONE': '15/47237824'},
 {'CNPJ_COMPLETO': 4181186714,
  'CEP': 2035020.0,
  'CORREIO_ELETRÔNICO': 'NICOLAS.PPAPA@GMAIL.COM',
  'NOME_FANTASIA': 'NICOLAS PALACIOS',
  'TELEFONE': '11/26050482'},
 {'CNPJ_COMPLETO': 25759075181,
  'CEP': 29370000.0,
  'CORREIO_ELETRÔNICO': 'sonia.cassandri@hotmail.com',
  'NOME_FANTASIA': 'None',
  'TELEFONE': '0/0'},
 {'CNPJ_COMPLETO': 6355294150,
  'CEP': 96825750.0,
  'CORREIO_ELETRÔNICO': 'None',
  'NOME_FANTASIA': 'None',
  'TELEFONE': 'nan/nan'},
 {'CNPJ_COMPLETO': 15534700133,
  'CEP': 37498000.0,
  'CORREIO_ELETRÔNICO': 'jairmbueno@yahoo.com.br',
  'NOME_FANTASIA': 'None',
  'TELEFONE': '35/32441217'},
 {'CNPJ_COMPLETO': 25320578156,
  'CEP': 12951280.0,
  'CORREIO_ELETRÔNICO': 'CONCEITONIC@GMAIL.COM',
  'NOME_FANTASIA': 'DISTRIBUIDORA DE BEBIDAS ARAUJO',
  'TELEFONE': '11/44119688'},
 {'CNPJ_COMPLETO': 13190217153,
  'CEP': 15200000.0,
  'CORREIO_ELETRÔNICO': 'LARISSAaNHOATO@HOTMAIL.COM',
  'NOME_FANTASIA': 'None',
  'TELEFONE': '17/32454095'},
 {'CNPJ_COMPLETO': 37253729180,
  'CEP': 8223000.0,
  'CORREIO_ELETRÔNICO': 'DSILVA@BREVITY.COM.BR',
  'NOME_FANTASIA': 'I R D GAS',
  'TELEFONE': '11/34935448'}]

# PyMongo

In [24]:
### Importando bibliotecas para conexão com o MongoDB

import pymongo
import json

In [25]:
### Conectando ao MongoDB

client = pymongo.MongoClient('mongodb://mongoadmin:password@localhost:27018/')
db = client['estabelecimentos']
print(db)

Database(MongoClient(host=['localhost:27018'], document_class=dict, tz_aware=False, connect=True), 'estabelecimentos')

In [26]:
### Inserindo dados no MongoDB

db.dados.insert_many(estabelecimentos_data)

# Elastic Search

In [12]:
### Importando bibliotecas para conexão com o Elasticsearch

import elasticsearch
print(elasticsearch.__version__)

(7, 17, 9)

In [27]:
### Conectando ao Elasticsearch

es = elasticsearch.Elasticsearch([{'host': 'localhost', 'port': 9200}])
resp = es.info()

c:\Users\levim\Documents\Github\avaliacao-flask\flask_venv\Lib\site-packages\elasticsearch\connection\base.py:200: ElasticsearchWarning: Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.17/security-minimal-setup.html to enable security.
  warnings.warn(message, category=ElasticsearchWarning)

In [32]:
### Inserindo dados no Elasticsearch

estabelecimentos_data = df.to_dict(orient = "records")
for data in estabelecimentos_data: 
  es.index(index='estabelecimentos', document=data)

c:\Users\levim\Documents\Github\avaliacao-flask\flask_venv\Lib\site-packages\elasticsearch\connection\base.py:200: ElasticsearchWarning: Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.17/security-minimal-setup.html to enable security.
  warnings.warn(message, category=ElasticsearchWarning)

In [33]:
### Buscando dados no Elasticsearch

res = es.search(index="estabelecimentos", body={'size':1000, "query": {"match_all": {}}})
print("Got %d Hits:" % res['hits']['total']['value'])

for hit in res['hits']['hits']:
    print("%(CNPJ_COMPLETO)s %(NOME_FANTASIA)s: %(TELEFONE)s" % hit["_source"])

Got 10 Hits:
10782307145 D REI MALHARIA: 91/34461250
1192680155 None: nan/nan
48894826178 None: 15/47237824
4181186714 NICOLAS PALACIOS: 11/26050482
25759075181 None: 0/0
6355294150 None: nan/nan
15534700133 None: 35/32441217
25320578156 DISTRIBUIDORA DE BEBIDAS ARAUJO: 11/44119688
13190217153 None: 17/32454095
37253729180 I R D GAS: 11/34935448

C:\Users\levim\AppData\Local\Temp\ipykernel_5512\58570679.py:3: DeprecationWarning: The 'body' parameter is deprecated for the 'search' API and will be removed in a future version. Instead use API parameters directly. See https://github.com/elastic/elasticsearch-py/issues/1698 for more information
  res = es.search(index="estabelecimentos", body={'size':1000, "query": {"match_all": {}}})